### ISSUE TITLE
"Slice bounds out of range" Issue building project in Windows

### ISSUE THREAD

**Issue by torresashjian** [TIBCOSoftware/flogo-cli#46]
Following issue building flogo project in Windows:

C:\GoFlogoWorkspace\bin\test>flogo build
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/TIBCOSoftware/flogo-cli/app.refPath(0xc0420dd140, 0x27, 0xc04202da40, 0x66, 0x1, 0xc0420694e0)
       C:/GoFlogoWorkspace/src/github.com/TIBCOSoftware/flogo-cli/app/api.go:304 +0xa4
github.com/TIBCOSoftware/flogo-cli/app.ListDependencies.func1(0xc04202da40, 0x66, 0x89daa0, 0xc0420f7320, 0x0, 0x0, 0x0, 0x66)
       C:/GoFlogoWorkspace/src/github.com/TIBCOSoftware/flogo-cli/app/api.go:247 +0x496
path/filepath.walk(0xc04202da40, 0x66, 0x89daa0, 0xc0420f7320, 0xc0420dd230, 0x0, 0x0)
       C:/Go/src/path/filepath/path.go:351 +0x88
path/filepath.walk(0xc0420f6c60, 0x5a, 0x89daa0, 0xc0420f6cc0, 0xc0420dd230, 0x0, 0x0)
       C:/Go/src/path/filepath/path.go:376 +0x41b
path/filepath.walk(0xc0420f6960, 0x55, 0x89daa0, 0xc0420f69c0, 0xc0420dd230, 0x0, 0x0)
       C:/Go/src/path/filepath/path.go:376 +0x41b
path/filepath.walk(0xc0420dfcc0, 0x4e, 0x89daa0, 0xc0420f65a0, 0xc0420dd230, 0x0, 0x0)
       C:/Go/src/path/filepath/path.go:376 +0x41b
path/filepath.walk(0xc0420d5780, 0x40, 0x89daa0, 0xc0420f6480, 0xc0420dd230, 0x0, 0x0)
       C:/Go/src/path/filepath/path.go:376 +0x41b
path/filepath.walk(0xc0420d5200, 0x32, 0x89daa0, 0xc0420e03c0, 0xc0420dd230, 0x0, 0x0)
       C:/Go/src/path/filepath/path.go:376 +0x41b
path/filepath.walk(0xc0420dd140, 0x27, 0x89daa0, 0xc0420e02a0, 0xc0420dd230, 0x0, 0x30)
       C:/Go/src/path/filepath/path.go:376 +0x41b
path/filepath.Walk(0xc0420dd140, 0x27, 0xc0420dd230, 0xc042069c28, 0x4f475e)
       C:/Go/src/path/filepath/path.go:398 +0x153
github.com/TIBCOSoftware/flogo-cli/app.ListDependencies(0x89e440, 0xc0420342a0, 0x0, 0x1, 0x746810, 0x2, 0xc0420de140, 0xc0420e0240)
       C:/GoFlogoWorkspace/src/github.com/TIBCOSoftware/flogo-cli/app/api.go:294 +0xfc
github.com/TIBCOSoftware/flogo-cli/app.generateGoMetadatas(0x89e440, 0xc0420342a0, 0xc04209fd80, 0x20)
       C:/GoFlogoWorkspace/src/github.com/TIBCOSoftware/flogo-cli/app/api.go:320 +0x49
github.com/TIBCOSoftware/flogo-cli/app.PrepareApp(0x89e440, 0xc0420342a0, 0xc04209ed40, 0x0, 0x0)
       C:/GoFlogoWorkspace/src/github.com/TIBCOSoftware/flogo-cli/app/api.go:113 +0x90
github.com/TIBCOSoftware/flogo-cli/app.BuildApp(0x89e440, 0xc0420342a0, 0xc042069e10, 0xc0420342a0, 0x2)
       C:/GoFlogoWorkspace/src/github.com/TIBCOSoftware/flogo-cli/app/api.go:166 +0x224
github.com/TIBCOSoftware/flogo-cli/app.(*cmdBuild).Exec(0xc042008e10, 0xc042002760, 0x0, 0x0, 0x0, 0x0)
       C:/GoFlogoWorkspace/src/github.com/TIBCOSoftware/flogo-cli/app/build.go:58 +0xf9
github.com/TIBCOSoftware/flogo-cli/cli.ExecCommand(0xc042034240, 0x89b920, 0xc042008e10, 0xc042002760, 0x0, 0x0, 0x0, 0x748246)
       C:/GoFlogoWorkspace/src/github.com/TIBCOSoftware/flogo-cli/cli/command.go:114 +0xb0
main.main()
       C:/GoFlogoWorkspace/src/github.com/TIBCOSoftware/flogo-cli/cmd/flogo/main.go:42 +0x129

**Comment by torresashjian** [comment]
Fixed by https://github.com/TIBCOSoftware/flogo-cli/issues/46
