### ISSUE TITLE
app name in flogo json not matching dir name

### ISSUE THREAD

**Issue by mellistibco** [TIBCOSoftware/flogo-cli#74]
When the app name specified in flogo json does not match the dir name, the app fails to execute after being built.

2017-11-21 08:44:37.070 DEBUG  [engine] - Registering action factory: 'github.com/TIBCOSoftware/flogo-contrib/action/flow'
2017-11-21 08:44:37.071 DEBUG  [engine] - Registering activity: 'github.com/TIBCOSoftware/flogo-contrib/activity/log'
2017-11-21 08:44:37.071 DEBUG  [engine] - Registering trigger factory: 'github.com/TIBCOSoftware/flogo-contrib/trigger/rest'
2017-11-21 08:44:37.071 INFO   [engine] - Engine: Starting...
2017-11-21 08:44:37.071 ERROR  [engine] - Engine: Error Creating trigger instances - Trigger Factory 'github.com/ecarlier-tibco/flogo/trigger/syslogs' not registered
panic: Engine: Error Creating trigger instances - Trigger Factory 'github.com/ecarlier-tibco/flogo/trigger/syslogs' not registered

goroutine 1 [running]:
github.com/TIBCOSoftware/flogo-lib/engine.(*EngineConfig).Init(0xc420016820, 0x0, 0x1, 0xc420011e20)
	/Users/mellis/flogo-apps/sysapp1/vendor/src/github.com/TIBCOSoftware/flogo-lib/engine/engine.go:85 +0x804
github.com/TIBCOSoftware/flogo-lib/engine.(*EngineConfig).Start(0xc420016820, 0x15a6260, 0xc420016820)
	/Users/mellis/flogo-apps/sysapp1/vendor/src/github.com/TIBCOSoftware/flogo-lib/engine/engine.go:126 +0x143
main.main()
	/Users/mellis/flogo-apps/sysapp1/src/sysapp1/main.go:37 +0xaa

**Comment by mellistibco** [comment]
Resolved.
